- addons/m1014/CfgWeapons.hpp
- addons/saiga12/config.cpp
- Popup Fix
- Remove unnecessary inheritance
> M1014 magwell error fix

- addons/main/script_macros.hpp
- addons/main/script_version.hpp
> Version change

- addons/ammunition/CfgAmmo.hpp
- addons/ammunition/CfgMagazines.hpp
- addons/ammunition/stringtable.xml
- addons/glock/CfgWeapons.hpp
- addons/glock/stringtable.xml
- addons/scar/CfgWeapons.hpp
- addons/scar/stringtable.xml
- Added stringtables to Ammo, Glocks and SCAR components.
> Add Stringtables

- addons/ammunition/CfgAmmo.hpp
- addons/ammunition/CfgMagazineWells.hpp
- addons/ammunition/CfgMagazines.hpp
- addons/ammunition/config.cpp
- addons/ammunition/stringtable.xml
- addons/glock/CfgWeapons.hpp
- addons/glock/stringtable.xml
- addons/scar/CfgWeapons.hpp
- addons/scar/stringtable.xml
- Added PMAG/EMAG variants of M855, M995, MK262 & MK318.
- Updated Stringtables.
- Changed 000 Buckshot to 00 Magnum
> Add PMAG/EMAG Magazines

- addons/ammunition/CfgMagazines.hpp
- addons/ammunition/stringtable.xml
- addons/glock/CfgWeapons.hpp
- addons/remass/$PBOPREFIX$
- addons/remass/BI.hpp
- addons/remass/CUP.hpp
- addons/remass/CfgMagazines.hpp
- addons/remass/NiArms.hpp
- addons/remass/config.cpp
- addons/remass/script_component.hpp
- addons/scar/CfgWeapons.hpp
- Balanced mass of items by making them consistent across CUP/NiArms and Vanilla.
> Overhaul Mass of magazines for consistency

- addons/rename/CfgMagazines.hpp
- addons/rename/CfgWeapons.hpp
- addons/rename/README.md
- addons/rename/config.cpp
- addons/rename/stringtable.xml
- Rename MX rifles for naming conformity
- Add ammunition type to magazines.
> Renaming MX Series And Ammunition

- addons/ak/config.cpp
- addons/ammunition/CfgMagazines.hpp
- addons/ammunition/config.cpp
- addons/glock/CfgWeapons.hpp
- addons/glock/config.cpp
- addons/l85/config.cpp
- addons/m1014/config.cpp
- addons/main/script_macros.hpp
- addons/mp5/config.cpp
- addons/mp7/config.cpp
- addons/remass/config.cpp
- addons/rename/CfgMagazines.hpp
- addons/rename/CfgWeapons.hpp
- addons/rename/config.cpp
- addons/saiga12/config.cpp
- addons/scar/CfgWeapons.hpp
- addons/scar/config.cpp
- addons/sg510/config.cpp
- addons/special/CfgWeapons.hpp
- addons/special/config.cpp
> Convert All Stringtable Entries To CSTRING

- addons/duplicates/$PBOPREFIX$
- addons/duplicates/CfgAmmo.hpp
- addons/duplicates/CfgWeapons.hpp
- addons/duplicates/config.cpp
- addons/duplicates/script_component.hpp
- Hide things that already exist in better quality/performance.
- Using scope = 1 to prevent breaking anything using the items already.
(Tested and working)
> Add Duplicates Component

- addons/ak/CfgSoundSets.hpp
- addons/ammunition/CfgMagazineWells.hpp
- addons/duplicates/CfgAmmo.hpp
- addons/duplicates/CfgWeapons.hpp
- addons/m1014/CfgSoundShaders.hpp
- addons/remass/BI.hpp
- addons/rename/CfgMagazines.hpp
- addons/rename/CfgWeapons.hpp
- addons/rfb/CfgAmmo.hpp
- addons/rfb/CfgMagazines.hpp
- addons/rfb/CfgWeapons.hpp
- addons/scar/CfgWeapons.hpp
> Remove Trailing Whitespace

- .gitignore
- addons/misc/$PBOPREFIX$
- addons/misc/CfgMagazines.hpp
- addons/misc/CfgWeapons.hpp
- addons/misc/config.cpp
- addons/misc/script_component.hpp
- addons/special/CfgFaces.hpp
- hemtt.toml
- Added Weapon & Ammo for private reasons
- Fixed 2 Hemtt build warnings
- Fixed an issue with Special Face being used on Units using those identities.
> Add Misc Component

- addons/flashlight/CfgWeapons.hpp
- addons/flashlight/config.cpp
- addons/special/CfgWeapons.hpp
- addons/special/config.cpp
- Removes Kellys special helmet
- Removes BWA3 required addons
> BWA3 Removal

- addons/gimmick/$PBOPREFIX$
- addons/gimmick/CfgAmmo.hpp
- addons/gimmick/CfgMagazineWells.hpp
- addons/gimmick/CfgMagazines.hpp
- addons/gimmick/CfgWeapons.hpp
- addons/gimmick/config.cpp
- addons/gimmick/script_component.hpp
- addons/gimmick/stringtable.xml
- Adds Gimmick variant of the MSBS rifle.
- Adds Red/Green magazines.
- Gimmick ammunition.
> Add Gimmick Component

- addons/ammunition/CfgMagazineWells.hpp
- addons/gimmick/stringtable.xml
- addons/m1014/CfgWeapons.hpp
- addons/rebalance/s4_lbt.hpp
- addons/remass/CUP.hpp
- addons/saiga12/CfgMagazines.hpp
- addons/saiga12/stringtable.xml
- Fix M1014 Magwells
- Fix Gimmick stringtable error
- Fix UBC errors with lbt vests from S4
- Remove Shotgun magazines from Remass component
- Update Saiga12 magazines to utilise new standard variants
> Update For New CUP Compatibility

- addons/ammunition/12g.hpp
- addons/ammunition/CfgMagazineWells.hpp
- addons/ammunition/CfgMagazines.hpp
- addons/ammunition/config.cpp
- addons/ammunition/stringtable.xml
Promet/MSBS Underbarrel-Shotgun:
- Adds 6Rnd Magnum buckshot shells
- Adds 6Rnd AP-20 Slug shells
> Adds Magnum Shells & AP-20 to Promet UB-SG

- addons/hlc_tweaks/$PBOPREFIX$
- addons/hlc_tweaks/CfgWeapons.hpp
- addons/hlc_tweaks/config.cpp
- addons/hlc_tweaks/script_component.hpp
For fixing NiArms content.
Currently sets `scope = 1` for an additional accessory state.
> Add HLC_Tweaks component

- addons/flashlight/ANPEQ_Black.hpp
- addons/flashlight/ANPEQ_OD.hpp
- addons/flashlight/ANPEQ_Tan.hpp
- addons/flashlight/ANPEQ_Top_Black.hpp
- addons/flashlight/ANPEQ_Top_OD.hpp
- addons/flashlight/ANPEQ_Top_Tan.hpp
- addons/flashlight/CfgWeapons.hpp
- addons/flashlight/LLM.hpp
- addons/flashlight/Surefire_Flashlights.hpp
- addons/flashlight/config.cpp
- addons/flashlight/script_component.hpp
- addons/flashlight/stringtable.xml
- Rewrite to make it more readable.
- Renames "High Power" to GT Edition
- Fixes MRT switching
- Adds low power red light to compliment NVG usage or CQB combat with NVG users.
> Flashlights - Rewrite and Expansion

- addons/ammunition/CfgMagazineWells.hpp
- Adds 7N21 9mm Ammo to the Scorpion Evo.
> Update Magazine Wells for 7N21 Ammunition

- addons/ammunition/762x51.hpp
- addons/ammunition/CfgMagazines.hpp
Magazine was tan instead of black.
> Ammunition - Fix Black M993 Scar-H Magazine

- addons/mk6/$PBOPREFIX$
- addons/mk6/CfgAmmo.hpp
- addons/mk6/config.cpp
- addons/mk6/script_component.hpp
Simulates the "whoosh" sounds emitted by incoming Mortars by using the sound for in-flight rounds.
> Add MK6 Component

- addons/deagle/$PBOPREFIX$
- addons/deagle/CfgWeapons.hpp
- addons/deagle/config.cpp
- addons/deagle/script_component.hpp
- Changes Desert Eagle firing sound from CUP to the MSBS Grot firing sound.
> Add Deagle Component

- addons/flashlight/CfgWeapons.hpp
- addons/flashlight/Handgun.hpp
- addons/flashlight/config.cpp
- addons/flashlight/stringtable.xml
- title.
- also fixes indentation on rail support.
> Flashlights - Add 2 Pistol IR/Laser/Light combos

- .github/workflows/arma.yml
> Add Artifact to continuous integration workflow

- addons/recoil/$PBOPREFIX$
- addons/recoil/CfgWeapons.hpp
- addons/recoil/config.cpp
- addons/recoil/script_component.hpp
- Fixes HK416 recoil to match SPAR-16 (Apex)
> Add Recoil Component

- addons/minigun/$PBOPREFIX$
- addons/minigun/CfgWeapons.hpp
- addons/minigun/config.cpp
- addons/minigun/script_component.hpp
- Switches the Vanilla 6.5 Minigun sound with the CUP M134 sound.
[Video](https://www.youtube.com/watch?v=UOs8zvUZuWA)
> Add Minigun Component

- addons/aug/$PBOPREFIX$
- addons/aug/CfgWeapons.hpp
- addons/aug/config.cpp
- addons/aug/script_component.hpp
- Adds select fire between Single / Full for the AUG A1, A2 & A3 variants.
> Add AUG Component

- addons/ammunition/CfgAmmo.hpp
- addons/rfb/CfgAmmo.hpp
- addons/socom/CfgAmmo.hpp
- Default values are probably better.
> Ammunition - Cleanup typicalSpeed

- addons/flares/CfgAmmo.hpp
> Flares - Extend flare lifetime to 3 minutes

- addons/flares/CfgAmmo.hpp
- addons/flares/config.cpp
> Flares - Add ACE Flares and cleanup config

- addons/flares/CfgAmmo.hpp
- Increases time to live & slows down descent.
> Flares - Improve 82mm Flares

- addons/duplicates/$PBOPREFIX$
- addons/duplicates/CfgAmmo.hpp
- addons/hidden/$PBOPREFIX$
- addons/hidden/CfgMagazines.hpp
- addons/hidden/CfgVehicles.hpp
- addons/hidden/config.cpp
- addons/hidden/script_component.hpp
- Hides things from CUP which are more of a hindrance.
- Merges Duplicates component into this one as it has the same functionality.
> Add Hidden Component

- addons/supplies/CfgVehicles.hpp
- addons/supplies/config.cpp
- addons/supplies/stringtable.xml
- title
- Requires this PR in Mods: https://github.com/Theseus-Aegis/Mods/pull/495
> Supplies - Remove NCO Medic Box

- addons/scar/CfgWeapons.hpp
- addons/scar/stringtable.xml
> SCAR - Add missing SCAR-H AFG Names, fix typo.

- addons/ammunition/CfgMagazineWells.hpp
- addons/ammunition/CfgMagazines.hpp
- addons/ammunition/magazines/545x39.hpp
- addons/ammunition/magazines/556x45.hpp
- addons/rename/CfgMagazines.hpp
- Renamed AK12/15/19 Magazines.
- Created new AP magazines for AK12/19 with new models.
> Rename, Ammunition - Add new AK12/19 Magazines.

- addons/special/CfgFaces.hpp
- addons/special/CfgWeapons.hpp
- Title
- Removes old comment.
> Special - Update displayName

- addons/supplies/CfgVehicles.hpp
- Adds a single surgical kit to Medical Supply Box.
> Supplies - Add Surgical Kit

- make_release.bat
> Tools - Run HEMTT Clean before Release Build

- addons/ammunition/CfgAmmo.hpp
- addons/ammunition/CfgMagazines.hpp
- addons/ammunition/handgun_magazines/10mm.hpp
- addons/special/CfgWeapons.hpp
- addons/special/config.cpp
- M11-10 Compact chambered in 10mm.
- Ammo stuff is done in ammunition component.
> Special - Add Zaks Special Item

- addons/sparebarrel/$PBOPREFIX$
- addons/sparebarrel/CfgWeapons.hpp
- addons/sparebarrel/README.md
- addons/sparebarrel/config.cpp
- addons/sparebarrel/script_component.hpp
- Halves the mass of the ACE Spare Barrel
> Add Spare Barrel Component

- addons/ammunition/CfgMagazines.hpp
- addons/ammunition/magazines/556x45.hpp
- addons/ammunition/magwells/rifle.hpp
- Add a 100Rnd and 200Rnd pouch for the CUP M249
- Add a 200Rnd box for the CUP m249
Since the Apex ones don't work, https://dev.cup-arma3.org/T4472
> Add 5.56 M249 Box & Pouch

- addons/entrenching/$PBOPREFIX$
- addons/entrenching/CfgVehicles.hpp
- addons/entrenching/README.md
- addons/entrenching/config.cpp
- addons/entrenching/script_component.hpp
- Adds entrenching tool abilities to backpacks with shovels.
(Requires GRAD update to work.)
> Add Entrenching Component

- addons/training/$PBOPREFIX$
- addons/training/CfgAmmo.hpp
- addons/training/CfgMagazines.hpp
- addons/training/CfgVehicles.hpp
- addons/training/CfgWeapons.hpp
- addons/training/README.md
- addons/training/config.cpp
- addons/training/script_component.hpp
- Adds training variants of several mines
I was trying to solve the problem of reseting an EOD training range, just made some training mines instead
> Add Training Component

- addons/ammunition/magazines/12g.hpp
- addons/ammunition/magazines/300Blackout.hpp
- addons/ammunition/magazines/45ACP.hpp
- addons/ammunition/magazines/46x30.hpp
- addons/ammunition/magazines/545x39.hpp
- addons/ammunition/magazines/556x45.hpp
- addons/ammunition/magazines/57x28.hpp
- addons/ammunition/magazines/58x42.hpp
- addons/ammunition/magazines/65x39.hpp
- addons/ammunition/magazines/68x43.hpp
- addons/ammunition/magazines/762x39.hpp
- addons/ammunition/magazines/762x51.hpp
- addons/ammunition/magazines/762x54r.hpp
- addons/ammunition/magazines/9x19.hpp
- addons/ammunition/magazines/9x39.hpp
Top right of UI where ammo info is. Tag shows on the left side of the box.
> Ammunition - Add magazine tags

- addons/ammunition/config.cpp
- addons/main/config.cpp
> Loadorders - WS & AoW

- addons/ammunition/CfgWeapons.hpp
> Ammunition - Fix R1 Magwells

- addons/arcadian/$PBOPREFIX$
- addons/arcadian/CfgMagazines.hpp
- addons/arcadian/CfgVehicles.hpp
- addons/arcadian/CfgWeapons.hpp
- addons/arcadian/README.md
- addons/arcadian/config.cpp
- addons/arcadian/script_component.hpp
- Switches Vanilla 6.5 ammo for GT 6.5 EPR.
> Add Arcadian Component

- addons/rpg/CfgAmmo.hpp
- MAAWS HE 44 now uses the same kind of fragmentation the RPG-7 does.
- Added the SPG-9 HE fragmentation
- Added the SPG-9 Infantry targeting
- Changed from high drag model of fragmentation.
> RPG - Additions

- addons/training/CfgAmmo.hpp
- addons/training/CfgVehicles.hpp
- Title
- Respect the [Coding Guidelines](https://ace3mod.com/wiki/development/coding-guidelines.html)
> Training - Fix AT Mine

- addons/recoils/ws/556/velko.hpp
> Fix UBC error from recoils

- addons/ammunition/CfgAmmo.hpp
- addons/ammunition/config.cpp
> Ammunition - Increase size of MELB tracers

- addons/ammunition/CfgMagazines.hpp
- addons/ammunition/CfgWeapons.hpp
- addons/ammunition/magazines/12g.hpp
- addons/ammunition/magazines/762x51.hpp
- addons/ammunition/magwells/rifle.hpp
- addons/recoils/CfgWeapons.hpp
- addons/recoils/ws/762N/slr.hpp
- Adds GT magwells to SLR & SA-77.
- New magazines for both.
- Slightly lowers AA12 magazine mass.
> Ammunition - Add new magazines for SLR/SA-77

- addons/flashlight/CfgVehicles.hpp
- addons/flashlight/config.cpp
> Flashlight - Improve floodlight power and distance

- addons/supplies/CfgVehicles.hpp
- Add 10x Toolkit to Engineer supplies in support of Repair changes.
> Supplies - Add 10x Toolkit to Engineer supplies

- .hemtt/hooks/post_release/01_rename_zip.rhai
- Rename final zip file.
**Requires HEMTT v1.5.0 (Rhai refactor) or higher!**
> Rename HEMTT release zip

- addons/supplies/CfgVehicles.hpp
> Supplies - Add rewritten breaching charge to engineer box

- addons/flares/CfgAmmo.hpp
- addons/recoils/cup/556/g36.hpp
- Required for next version of HEMTT.
> Flares/Recoils - Remove Duplicate Classes

- addons/replacements/config.cpp
- Describe what this pull request will do
- Each change in a separate line
- Respect the [Coding Guidelines](https://ace3mod.com/wiki/development/coding-guidelines.html)
Aready in #174 but I'd like this earlier if that pr is not ready to be merged yet
> Replacements - skip missing

- addons/recoils/niarms/weapons/556.hpp
> Fix Case sensitivity for HEMTT 1.9.0

- addons/ammunition/magwells/rifle.hpp
- addons/ammunition/ws/CfgMagazines.hpp
- addons/ammunition/ws/magazines/556x45.hpp
> Ammunition - Add 50Rnd Vektor Mags

- addons/flashlight/script_component.hpp
> Flashlight - Match ACE values for Visible Lasers

- addons/ammunition/CfgMagazines.hpp
- addons/ammunition/bi/magazines/762x39.hpp
- addons/ammunition/magwells/rifle.hpp
> Ammunition - Add Metal 75Rnd AK Drum Mags

- addons/arcadian/config.cpp
- addons/attachments/config.cpp
- addons/entrenching/config.cpp
- addons/flashlight/config.cpp
- addons/hidden/config.cpp
- addons/hlc_tweaks/config.cpp
- addons/markers/config.cpp
- addons/rebalance/config.cpp
- addons/recoils/config.cpp
- addons/recoils/cup/config.cpp
- addons/recoils/niarms/config.cpp
- addons/recoils/pi/config.cpp
- addons/scar/config.cpp
- addons/sparebarrel/config.cpp
- addons/supplies/config.cpp
- addons/theseus/config.cpp
- addons/training/config.cpp
- addons/uniforms/config.cpp
- addons/vehicles/config.cpp
> Cleanup non existent CfgPatches array

- addons/effects/$PBOPREFIX$
- addons/effects/CfgCloudlets.hpp
- addons/effects/Effects.hpp
- addons/effects/config.cpp
- addons/effects/script_component.hpp
- Adds small impact effects for explosions.
> Add Effects Component

- addons/uniforms/CfgVehicles.hpp
> Uniforms - Set CfgVehicles scope correctly

- addons/effects/CfgAmmo.hpp
- addons/effects/Effects.hpp
- addons/effects/config.cpp
- Adds the missing explosion effects
- Fixes 155mm Artillery explosion effect.
> Effects - Add missing effects & fix ammo.

- addons/uniforms/CfgWeapons.hpp
> Uniforms - Fix ground texture

- addons/recoils/cup/weapons/762N.hpp
- Was using non-existant recoil pattern.
> Recoils - Fix SCAR-H EGLM

- addons/ammunition/niarms/config.cpp
- addons/ammunition/ws/config.cpp
- NiArms and WS MagazineWells weren't included.
> Ammunition - Fix not included magwells

- addons/vehicles/CfgVehicles.hpp
- addons/vehicles/script_component.hpp
- Fix Macro
- Slightly raise values.
> Vehicles - Alter boat upgrade

- addons/replacements/CfgWeapons.hpp
- Title, (next TAC Mods release.)
> Replacements - Fix IFAK Bodybag Item

- addons/ammunition/cup/CfgMagazineWells.hpp
- addons/ammunition/cup/config.cpp
> Ammunition - Fix AK19 Magwell

- addons/rebalance/s4g/CfgWeapons.hpp
- addons/rebalance/s4g/script_component.hpp
- title
- Also fixes 0 weight vests
> Rebalance - Alter CPC capacity to match JPC

- addons/hlc_tweaks/CfgWeapons.hpp
- addons/hlc_tweaks/README.md
- addons/hlc_tweaks/config.cpp
- It's supposed to spawn with a suppressor, it didn't because config is hard.
> HLC Tweaks - Fix Honey Badger suppressor not being applied

- addons/resound/CfgWeapons.hpp
- addons/resound/script_component.hpp
- addons/resound/weapons/svd.hpp
- Match the VS-121 which is better.
> Resound - Change SVD Sounds

- addons/hidden_units/CfgFactionClasses.hpp
- addons/hidden_units/CfgGroups_West.hpp
- addons/hidden_units/CfgVehicles.hpp
- addons/hidden_units/CfgVehicles_Baseclasses.hpp
- addons/hidden_units/Vanilla_Units/una.hpp
- Replaced in TACU with our own variant of the UN.
> Hidden Units - Hide UNA Faction

- addons/training/CfgWeapons.hpp
> Training - Fix UBC

- addons/training/CfgVehicles.hpp
- Fixes the ammo for training tripwire and claymore
> Training: Fix tripwire and claymore

- addons/hlc_tweaks/CfgWeapons.hpp
> HLC Tweaks - Allow single fire on AUG HBARs

- addons/hlc_tweaks/CfgWeapons.hpp
- addons/hlc_tweaks/config.cpp
- addons/hlc_tweaks/hidden_attachments.hpp
- addons/hlc_tweaks/hidden_augRifles.hpp
- addons/hlc_tweaks/singleFire_AUG.hpp
- Hides all the stupid / broken attachments
- Hides the broken weapons
> HLC Tweaks - Hide all the weird NiArms attachments

- addons/effects/CfgLights.hpp
- addons/effects/config.cpp
- addons/effects/impactEffects.hpp
- Completely missed this the first time around, lights up the area where the effect happens, it's cool as shit.
> Effects - Add light to metal spark effect

- addons/walle/CfgAmmo.hpp
- addons/walle/config.cpp
- Firing creates huge lag spike, should fix.
> WallE - Possibly fix WallE

- addons/replacements/CfgWeapons.hpp
- title
- Shut up JJ I don't wanna hear it about premature releasing
> Replacements - Switch to ACE painkillers from tac ones

- .hemtt/project.toml
- Add launch config with minimal mods for quick testing
- `exteneds` requires the next version of HEMTT, but the default will work fine on previous / current versions
> Tools - HEMTT Launch Config

- addons/hidden/config.cpp
> Hidden - Fix requiredaddons

- addons/flashlight/CfgWeapons.hpp
- addons/flashlight/Surefire.hpp
- addons/flashlight/config.cpp
- addons/flashlight/joint_rails.hpp
> Flashlight - Add Surefire XC1

- addons/supplies/CfgVehicles.hpp
> Supplies - Add Black MAAWs to Launcher box

- addons/hidden/CfgMagazines.hpp
- No idea when this started happening but oh well.
> Hidden - Fix UBC on grenades

- addons/recoils/ws/weapons/762N.hpp
> Recoils - Add SLR Para recoils

- addons/ammunition/rf/CfgAmmo.hpp
- addons/ammunition/rf/CfgMagazineWells.hpp
- addons/ammunition/rf/CfgMagazines.hpp
- addons/ammunition/rf/magazines/127x55.hpp
- addons/ammunition/rf/magazines/50AE.hpp
- Adds GL rounds to GL magwells
- Adds Desert Eagle Mags
> Ammunition - Final RF

- addons/hidden_units/rf_ws/CfgVehicles.hpp
- addons/hidden_units/rf_ws/config.cpp
- addons/hidden_units/rf_ws/script_component.hpp
- Hides vehicles from the RF/WS compatibility data that bring back Deprecated factions
> Hidden Units - RF / WS Compat Data

- addons/recoils/CfgRecoils.hpp
- Slightly reduce SMG vertical recoils
> Recoils - Lower SMG Recoils

- addons/animations/$PBOPREFIX$
- addons/animations/config.cpp
- addons/animations/script_component.hpp
- Increases switch to handgun speed.
- Increases swim speed to more bearable and realistic.
- Increases ladder climbing speed.
> Add Animations Component

- addons/animations/CfgMovesMaleSdr.hpp
- addons/animations/config.cpp
- Looks like you're sniffing your hand and it drives me nuts.
> Animations - Remove sitting smoking idle animation

- addons/ammunition/rf/magazines/127x55.hpp
> Ammunition RF - Fix displayNameShort for ASh12

- .hemtt/project.toml
- addons/ammunition/aegis/CfgMagazineWells.hpp
- addons/ammunition/aegis/CfgMagazines.hpp
- addons/ammunition/aegis/CfgWeapons.hpp
- addons/ammunition/aegis/config.cpp
- addons/ammunition/aegis/magazines/545x39.hpp
- addons/ammunition/aegis/magazines/762x51.hpp
- addons/ammunition/aegis/script_component.hpp
- addons/ammunition/atlas/CfgMagazineWells.hpp
- addons/ammunition/atlas/CfgMagazines.hpp
- addons/ammunition/atlas/CfgWeapons.hpp
- addons/ammunition/atlas/config.cpp
- addons/ammunition/atlas/script_component.hpp
> Aegis & Atlas

- addons/ammunition/CfgAmmo.hpp
- addons/ammunition/CfgMagazines.hpp
- addons/ammunition/aegis/CfgMagazineWells.hpp
- addons/ammunition/aegis/CfgMagazines.hpp
- addons/ammunition/aegis/CfgWeapons.hpp
- addons/ammunition/aegis/config.cpp
- addons/ammunition/aegis/magazines/127x33.hpp
- addons/ammunition/aegis/magazines/57x28.hpp
- addons/ammunition/aegis/magazines/9x21.hpp
- addons/ammunition/bi/45ACP.hpp
- addons/ammunition/cup/CfgAmmo.hpp
- addons/ammunition/magwells/handgun.hpp
> Aegis - Pistols

- addons/hidden_units/rf_ws/CfgVehicles.hpp
- addons/hidden_units/rf_ws/config.cpp
- I love seeing me some "DEPRECATED" factions showing because of a single unit/vehicle.
> Hidden Units - Remove new RF/WS Units

- addons/hidden_units/CUP_Units/armed_forces_of_the_russian_federation.hpp
- addons/hidden_units/CUP_Units/army_of_the_czech_republic.hpp
- addons/hidden_units/CUP_Units/british_armed_forces.hpp
- addons/hidden_units/CUP_Units/bundeswehr.hpp
- addons/hidden_units/CUP_Units/chernarus_defense_forces.hpp
- addons/hidden_units/CUP_Units/chernarussian_movement_of_the_red_star.hpp
- addons/hidden_units/CUP_Units/horizon_islands_legion.hpp
- addons/hidden_units/CUP_Units/ion_pmc.hpp
- addons/hidden_units/CUP_Units/national_party_of_chernarus.hpp
- addons/hidden_units/CUP_Units/royal_army_corps_of_sahrani.hpp
- addons/hidden_units/CUP_Units/sahrani_liberation_army.hpp
- addons/hidden_units/CUP_Units/takistani_army.hpp
- addons/hidden_units/CUP_Units/takistani_locals.hpp
- addons/hidden_units/CUP_Units/takistani_militia.hpp
- addons/hidden_units/CUP_Units/ukraine.hpp
- addons/hidden_units/CUP_Units/united_nations.hpp
- addons/hidden_units/CUP_Units/united_states_army.hpp
- addons/hidden_units/CUP_Units/united_states_marine_corps.hpp
- addons/hidden_units/CfgVehicles_Turrets.hpp
- addons/hidden_units/CfgVehicles_Vehicles.hpp
- addons/hidden_units/Vanilla_Units/ctrg.hpp
- addons/hidden_units/rf_ws/CfgVehicles.hpp
- addons/hidden_units/ws/ctrg.hpp
- addons/hidden_units/ws/sfia.hpp
- addons/hidden_units/ws/una.hpp
> Hidden Units - Switch to macro

- addons/ammunition/aegis/script_component.hpp
> Ammunition - Aegis, fix typo.

- addons/ammunition/ws/CfgMagazineWells.hpp
- addons/ammunition/ws/CfgMagazines.hpp
- addons/ammunition/ws/magazines/556x45.hpp
> Ammunition WS - Add Surefire & Camo Stanag

- addons/ammunition/bi/65x39.hpp
- addons/ammunition/magwells/rifle.hpp
- addons/ammunition/script_macros.hpp
- addons/ammunition/ws/magazines/556x45.hpp
- Adds 6.5 Khaki mags
- Fixes unrelated typo that I noticed
> Ammunition - Khaki 6.5

- addons/ammunition/aegis/CfgWeapons.hpp
- Adds the CBA magwell for 5.56 mags to Aegis weapons
> Ammunition Aegis - 5.56 Drum Magwells

- addons/ammunition/script_macros.hpp
> Fix HEMTT warnings

- addons/armory/CfgGesturesMale.hpp
> Armory - Fix headbob mode

- addons/flares/CfgVehicles.hpp
- Removed the stringtable ages ago, just not the actual `CSTRING(x)` part.
> Flares - Fix missing stringtable entries

- addons/compat_rf/CfgAmmo.hpp
- addons/compat_rf/config.cpp
> Compat RF - Enable fragmentation for PSRL frag round

- addons/ammunition/CfgAmmo.hpp
- addons/ammunition/cup/CfgAmmo.hpp
- addons/ammunition/niarms/CfgAmmo.hpp
- addons/ammunition/rf/CfgAmmo.hpp
- addons/compat_rf/CfgAmmo.hpp
- addons/flashlight/script_macros.hpp
> HEMTT 1.14.7 suggestions

- addons/ammunition/niarms/CfgMagazines.hpp
- addons/ammunition/rf/CfgMagazines.hpp
- addons/ammunition/rf/magazines/10mm.hpp
- addons/special/CfgWeapons.hpp
- addons/special/config.cpp
- Switches from NiArms model to RF Glock19x, converted to 10mm.
- Classnames are still the same.
> Special - Update Zakharov item

- addons/flashlight/script_macros.hpp
- Current flashlights have the power and intensity of a sun. Now it's much lower.
> Flashlight - Lower distance

- addons/ammunition/niarms/CfgMagazineWells.hpp
- addons/ammunition/niarms/CfgMagazines.hpp
- addons/ammunition/niarms/magazines/556x45.hpp
> Ammunition - Add NiArms drum mags

- addons/ammunition/bi/45ACP.hpp
- addons/ammunition/bi/545x39.hpp
- addons/ammunition/bi/57x28.hpp
- addons/ammunition/bi/58x42.hpp
- addons/ammunition/bi/65x39.hpp
- addons/ammunition/bi/762x39.hpp
- addons/ammunition/bi/762x51.hpp
- addons/ammunition/bi/762x54r.hpp
- addons/ammunition/bi/9x19.hpp
- addons/ammunition/cup/magazines/45ACP.hpp
- addons/ammunition/cup/magazines/46x30.hpp
- addons/ammunition/cup/magazines/545x39.hpp
- addons/ammunition/cup/magazines/556x45.hpp
- addons/ammunition/cup/magazines/68x43.hpp
- addons/ammunition/cup/magazines/762x39.hpp
- addons/ammunition/cup/magazines/762x51.hpp
- addons/ammunition/cup/magazines/9x19.hpp
- addons/ammunition/cup/magazines/9x39.hpp
- addons/ammunition/niarms/magazines/300Blackout.hpp
- addons/ammunition/niarms/magazines/357.hpp
- addons/ammunition/niarms/magazines/556x45.hpp
- addons/ammunition/niarms/magazines/9x19.hpp
- addons/ammunition/rf/magazines/10mm.hpp
- addons/ammunition/rf/magazines/127x55.hpp
- addons/ammunition/rf/magazines/50AE.hpp
- addons/ammunition/rf/magazines/556x45.hpp
- addons/ammunition/rf/magazines/9x19.hpp
- addons/ammunition/ws/magazines/556x45.hpp
- addons/ammunition/ws/magazines/762x51.hpp
> Ammunition - Tracers every 4

- addons/ammunition/aegis/CfgMagazineWells.hpp
- addons/ammunition/aegis/CfgMagazines.hpp
- addons/ammunition/aegis/magazines/545x39.hpp
- Add 45Rnd RPK mag from aegis
- Add 60Rnd RPK mag from aegis
> aegis: add aegis 5.45 RPK mags
