- addons/ammunition/CfgMagazines.hpp
- addons/ammunition/stringtable.xml
- addons/glock/CfgWeapons.hpp
- addons/glock/stringtable.xml
- addons/rename/$PBOPREFIX$
- addons/rename/CfgMagazines.hpp
- addons/rename/CfgWeapons.hpp
- addons/rename/README.md
- addons/rename/config.cpp
- addons/rename/script_component.hpp
- addons/rename/stringtable.xml
- addons/scar/CfgWeapons.hpp
- addons/scar/stringtable.xml
- Start of renaming 5.56 magazines
- Start of 7.62 magazines
- Temporarily rename ACE 2D Optics to the ACE Realistic names format until it's released in ACE.
- Will be sporadically updated with changes over time.
> Add Rename component

- addons/ak/CfgSoundSets.hpp
- addons/ak/config.cpp
- addons/ammunition/CfgAmmo.hpp
- addons/ammunition/CfgMagazineWells.hpp
- addons/ammunition/CfgMagazines.hpp
- addons/ammunition/config.cpp
- addons/ammunition/stringtable.xml
- addons/glock/CfgWeapons.hpp
- addons/glock/config.cpp
- addons/l85/config.cpp
- addons/m1014/CfgSoundSets.hpp
- addons/m1014/CfgSoundShaders.hpp
- addons/m1014/config.cpp
- addons/main/script_macros.hpp
- addons/mp5/CfgMagazineWells.hpp
- addons/mp5/config.cpp
- addons/mp7/config.cpp
- addons/remass/BI.hpp
- addons/remass/CfgMagazines.hpp
- addons/rename/CfgMagazines.hpp
- addons/rename/README.md
- addons/rename/stringtable.xml
- addons/saiga12/config.cpp
- addons/scar/config.cpp
- addons/sg510/CfgSoundSets.hpp
- addons/sg510/config.cpp
- Overhaul ammunitions.
- Add M855A1 rounds for SPW/HK416 Drum Mags
- Add PMAG/EMAG Variants for M855, M856, M855A1, M955, MK262, MK318 ammo types.
- Add ammunition designations to vanilla magazines, PS, M80, M62, SS190 & Luger.
- Add 7.62x39 magazines to Remass.
> Add PMAG/EMAG Variants and Overhaul Ammunition

- addons/saiga12/CfgMagazines.hpp
- addons/saiga12/config.cpp
- addons/saiga12/stringtable.xml
- Classnames are 8Rnd and 20Rnd, but are currently set as 5Rnd and 12Rnd both magazines are now upped to match classnames.
- Display names are also changed to match new ammo count.
> Correct Saiga12k Magazine Sizes

- addons/rebalance/$PBOPREFIX$
- addons/rebalance/CfgVehicles.hpp
- addons/rebalance/CfgWeapons.hpp
- addons/rebalance/config.cpp
- addons/rebalance/milgp_jpc.hpp
- addons/rebalance/milgp_marciras.hpp
- addons/rebalance/milgp_mmac.hpp
- addons/rebalance/s4_cpc.hpp
- addons/rebalance/s4_lbt.hpp
- addons/rebalance/script_component.hpp
Balances vest armour values to match Vanilla counterparts.
- Rebalanced MarCiras/MMAC/JPC vests from Milgp
- Rebalanced S4/LBT vests from Spec4Gear
- Fixed abnormally high load of the Fatpack backpacks (matching Assault Packs)
> Add Rebalance Component

- addons/flares/$PBOPREFIX$
- addons/flares/CfgAmmo.hpp
- addons/flares/CfgVehicles.hpp
- addons/flares/config.cpp
- addons/flares/script_component.hpp
- addons/flares/stringtable.xml
- Updates Editor & Zeus module list to include Parachute and Cluster flares in Red/White/Green
- Increased lifetime of cluster flares from 7s > ~60s
Requested by @jonpas
> Update Flare Module to utilise CUP flares

- addons/ammunition/9x19.hpp
- addons/ammunition/CfgAmmo.hpp
- addons/ammunition/CfgMagazineWells.hpp
- addons/ammunition/CfgMagazines.hpp
- addons/ammunition/config.cpp
- addons/ammunition/stringtable.xml
- addons/mp5/$PBOPREFIX$
- addons/mp5/CfgWeapons.hpp
- addons/mp5/config.cpp
- addons/mp5/script_component.hpp
- addons/rename/README.md
MP5 Fix:
Easy workaround by changing it's magwell to it's own class so it can only access CUP MP5 magazines which show on the model.
7N21 Ammunition for CUP MP5/All Vanilla 9x19 weapons.
> Expand 9x19 Ammunition & MP5 model fix

- addons/flashlight/ANPEQ_Black.hpp
- addons/flashlight/ANPEQ_OD.hpp
- addons/flashlight/ANPEQ_Tan.hpp
- addons/flashlight/ANPEQ_Top_Black.hpp
- addons/flashlight/ANPEQ_Top_OD.hpp
- addons/flashlight/ANPEQ_Top_Tan.hpp
- addons/flashlight/LLM.hpp
- addons/flashlight/Surefire_Flashlights.hpp
- addons/flashlight/stringtable.xml
Added names for attachment states:
- Flashlight Blue
- Flashlight Red
- IR Laser
- Visible Laser
---
- Fixed name of LLM MKIII
- Fixed Visible pointer of LLM MKIII
> Flashlight - Fix LLM MKIII & Add switch state names

- optionals/rpg/$PBOPREFIX$
- optionals/rpg/CfgAmmo.hpp
- optionals/rpg/CfgWeapons.hpp
- optionals/rpg/config.cpp
- optionals/rpg/script_component.hpp
- Allows AI to fire RPGs at infantry.
Set this as an optional because even i don't know if this is a good idea. Would require some serious testing before being implemented permanently.
> Add Optional RPG Component

- addons/bnae/$PBOPREFIX$
- addons/bnae/CfgWeapons.hpp
- addons/bnae/config.cpp
- addons/bnae/script_component.hpp
- Fixes RK-95 railed that had no weight and couldn't take suppressors. (Creates a UBC error, but so does the ACE compat fix)
> Add Bnae component

- addons/lamg/CfgRecoils.hpp
- addons/recoil/CfgWeapons.hpp
- addons/recoil/config.cpp
- all SIG SGxxx rifles have abnormal vertical recoil, changed to the Spar-16 from APEX.
- LAMG horizontal recoil spread is still high, lowered by 0.1.
> Recoil - Fix Sig SG rifle recoil and tweak LAMG recoil

- addons/lamg/CfgRecoils.hpp
- addons/lamg/CfgWeapons.hpp
- Split LAMG / Stoner 99 recoils.
- LAMG recoil has a tighter spread than regular Stoner 99 to differentiate between weight difference.
> LAMG - Improve LAMG Recoil Spread

- addons/ammunition/CfgWeapons.hpp
- addons/ammunition/config.cpp
Added missing magwells to:
- SCAR-H EGLM & Black variant
- SCAR-H CQC EGLM & Black variant
- PDW
- R1 Enhanced
> Ammunition - Add missing magwells

- addons/ammunition/CfgAmmo.hpp
- addons/ammunition/script_component.hpp
- Changes ammo inheritance classes to Vanilla Tracers or CUP Tracers.
Diffchecker shows my classes and vanilla are exactly the same except no tracers show. No idea why.
> Ammunition - Fix SMG tracers not working

- addons/ammunition/CfgAmmo.hpp
- addons/ammunition/magazines/57x28.hpp
- Removes excess 5.7x28 magazines, all ammo is considered AP anyway.
- Lowered Ball rounds caliber to < 0.5 for most ammo.
- Added ACE ballistics properties (to any that have them from ACE wiki.)
- Because `caliber` seemingly only affects Vehicles/Terrain objects, it's implemented only for that purpose really as BI implemented body armour in the laziest way imaginable.
- Hit values go up with Ball, EPR, AP. (Balanced by pricing in armory)
Included a mission file for testing (with values as hints, targets at 100/200/300m.)
[bulletTesting.VR.zip](https://github.com/Theseus-Aegis/GTArmory/files/9766366/bulletTesting.VR.zip)
> Ammunition - Penetration fixes

- addons/ammunition/magazines/556x45.hpp
- addons/ammunition/script_component.hpp
- Uses new CUP PMAG without the QP and fixes the UI issue.
- Renames Tan to Coyote because "Shit-Brown" isn't tan.
fix (#120) fix (#121)
> Ammunition - New PMAG model without QP

- addons/ammunition/CfgAmmo.hpp
- addons/ammunition/CfgWeapons.hpp
- addons/ammunition_ai/$PBOPREFIX$
- addons/ammunition_ai/CfgAmmo.hpp
- addons/ammunition_ai/CfgMagazineWells.hpp
- addons/ammunition_ai/CfgMagazines.hpp
- addons/ammunition_ai/README.md
- addons/ammunition_ai/config.cpp
- addons/ammunition_ai/script_component.hpp
Intended to be used for TAC Units, slightly improved ammo, different tracers.
Works with normal weapons but can't be stashed.
> Add AI Ammunition Component

- addons/ammunition/CfgAmmo.hpp
- addons/ammunition/CfgMagazines.hpp
- addons/ammunition/magazines/300Blackout.hpp
- Fix required for next NiArms version.
- Converts 300 Blackout from subsonic to ball.
- Changes parent mag because it wouldn't overwrite tracer values for some reason.
> Ammunition - NiArms Fix

- addons/weapons/CfgWeapons.hpp
- addons/weapons/vanilla_overwrites.hpp
Vanilla machineguns automatically come with bipods. Doesn't really work for a system where you buy them.
> Weapons - Remove Bipods from Vanilla MGs

- addons/ammunition/cup/CfgMagazines.hpp
- addons/ammunition/cup/magazines/762x51.hpp
- addons/ammunition/magwells/rifle.hpp
- Vanilla ones don't fit correctly, alternative ones should be available.
> Ammunition - Add CUP HK417 Magazines

- addons/supplies/config.cpp
> Supplies - Fix Fuel canister not showing in Zeus

- addons/nvg/$PBOPREFIX$
- addons/nvg/CfgWeapons.hpp
- addons/nvg/config.cpp
- addons/nvg/script_component.hpp
- Currently just adds GPNVGs in White Phosphor. (Requires ACE 3.16.1 because of ace prefix on `colorPreset`.)
> Add NVG Component

- addons/ammunition/CfgAmmo.hpp
- addons/ammunition/cup/magazines/300WM.hpp
- Sets 300WM mags to actually use it because it's more powerful than 7.62x54r
> Ammunition - Add 300WM ammo

- addons/training/CfgAmmo.hpp
- addons/training/CfgMagazines.hpp
- addons/training/CfgWeapons.hpp
- Adds training smokes
- Lifetime of 2 seconds instead of 60
Great for training with placement and signalling without having to deal with the smoke lingering
> Training - Smoke Grenades

- addons/ammunition/cup/CfgMagazineWells.hpp
- addons/ammunition/cup/CfgMagazines.hpp
- addons/ammunition/cup/magazines/556x45.hpp
- addons/ammunition/niarms/CfgMagazineWells.hpp
- addons/ammunition/niarms/CfgMagazines.hpp
- addons/ammunition/niarms/magazines/556x45.hpp
- Switches the 30Rnd mags from NiArms variants to CUPs, Don't like the stupid clear mags.
- Can't do anything about the 42Rnd ones but oh well.
- Classnames are the same, transition should be seamless.
> Ammunition - Switch from NiArms AUG mags to CUP

- addons/effects/CfgCloudlets.hpp
- addons/effects/blastwaveEffects.hpp
- addons/effects/config.cpp
- addons/effects/impactEffects.hpp
**Blastwave Stuff**
- Forces the refraction effect to show on every player regardless of video settings.
- Disable blocking AI visibility on refraction effect (supposedly better performance)
**Impact Effects**
- Increase the bullet hit effect on the ground and other objects slightly, makes it more visible (ground & walls)
- Adds a sparking effect for hitting metal, only in effect on high particle settings for performance reasons.
> Effects - Add Sparks & Increase impact effect size
